name: "Deployment"
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install Dependencies"
        run: cd ./import/
        run: npm ci
        run: cd ..
        run: npm ci
        run: npm run predeploy
      - name: "Github Pages Deployment"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -u "github-actions-bot <support+actions@github.com>"
        if: ${{ github.ref == 'refs/heads/master' }} # only deploy master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}